FROM fedora:37 AS builder

WORKDIR /build

RUN dnf update -y && \
    dnf install -y git-core golang make shellcheck which && \
    dnf install -y https://github.com/golangci/golangci-lint/releases/download/v1.50.1/golangci-lint-1.50.1-linux-amd64.rpm

COPY ./ /build
RUN go mod download

RUN make check
