// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package cohabdb

import (
	"database/sql"
)

type Session struct {
	ID                   int64
	UserID               sql.NullInt64
	CreatedAt            int64
	IsLoggedIn           bool
	GoogleForceApproval  bool
	ContactGroupsJson    sql.NullString
	SelectedResourceName sql.NullString
}

type User struct {
	ID      int64
	Sub     string
	Name    sql.NullString
	Picture sql.NullString
	Token   sql.NullString
}
