// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package cohabdb

import (
	"database/sql"
)

type Session struct {
	ID         int64
	UserID     sql.NullInt64
	CreatedAt  int64
	IsLoggedIn bool
}

type Token struct {
	ID     int64
	UserID int64
	Token  string
}

type User struct {
	ID       int64
	Sub      string
	FullName sql.NullString
}
