// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package cohabdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ExpireSession(ctx context.Context, id int64) error
	GetSession(ctx context.Context, id int64) (Session, error)
	GetToken(ctx context.Context, id int64) (sql.NullString, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserBySession(ctx context.Context, id int64) (User, error)
	UpdateContactGroupsJSON(ctx context.Context, arg UpdateContactGroupsJSONParams) error
	UpdateGoogleForceApproval(ctx context.Context, arg UpdateGoogleForceApprovalParams) error
	UpdateSelectedResourceName(ctx context.Context, arg UpdateSelectedResourceNameParams) error
	UpdateTokenBySession(ctx context.Context, arg UpdateTokenBySessionParams) error
}

var _ Querier = (*Queries)(nil)
