name: shellcheck

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3

      - name: run ShellCheck
        uses: ludeeus/action-shellcheck@master
